.nh
.TH "bitcensus" "1" "Apr 2024" "" ""

.SH NAME
.PP
bitcensus-doc-md - Generate markdown documentation for bitcensus


.SH SYNOPSIS
.PP
\fBbitcensus doc md [flags]\fP


.SH DESCRIPTION
.PP
Generate markdown documentation for bitcensus


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for md


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--config\fP=""
	config file (default is $XDG_CONFIG_HOME/bitcensus.json)

.PP
\fB--log-json\fP[=false]
	output json logs

.PP
\fB--log-level\fP="info"
	log level

.PP
\fB-o\fP, \fB--output\fP="."
	documentation output path


.SH SEE ALSO
.PP
\fBbitcensus-doc(1)\fP
