.nh
.TH "bitcensus" "1" "Dec 2023" "" ""

.SH NAME
.PP
bitcensus - A file system census utility


.SH SYNOPSIS
.PP
\fBbitcensus [flags]\fP


.SH DESCRIPTION
.PP
A file system census utility


.SH OPTIONS
.PP
\fB--config\fP=""
	config file (default is $XDG_CONFIG_HOME/bitcensus.json)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for bitcensus

.PP
\fB--log-json\fP[=false]
	output json logs

.PP
\fB--log-level\fP="info"
	log level


.SH SEE ALSO
.PP
\fBbitcensus-completion(1)\fP, \fBbitcensus-doc(1)\fP, \fBbitcensus-export(1)\fP, \fBbitcensus-import(1)\fP, \fBbitcensus-sync(1)\fP, \fBbitcensus-verify(1)\fP
