.nh
.TH "bitcensus" "1" "Apr 2024" "" ""

.SH NAME
.PP
bitcensus-doc - Generate documentation for bitcensus


.SH SYNOPSIS
.PP
\fBbitcensus doc [flags]\fP


.SH DESCRIPTION
.PP
Generate documentation for bitcensus


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for doc

.PP
\fB-o\fP, \fB--output\fP="."
	documentation output path


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--config\fP=""
	config file (default is $XDG_CONFIG_HOME/bitcensus.json)

.PP
\fB--log-json\fP[=false]
	output json logs

.PP
\fB--log-level\fP="info"
	log level


.SH SEE ALSO
.PP
\fBbitcensus(1)\fP, \fBbitcensus-doc-man(1)\fP, \fBbitcensus-doc-md(1)\fP
