// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: parity/v0/Packet.proto

package parityv0

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IndexPacket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockSize          uint64 `protobuf:"varint,1,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"`
	ShardCount         uint64 `protobuf:"varint,2,opt,name=shard_count,json=shardCount,proto3" json:"shard_count,omitempty"`
	RecoveryShardCount uint64 `protobuf:"varint,3,opt,name=recovery_shard_count,json=recoveryShardCount,proto3" json:"recovery_shard_count,omitempty"`
	CodeMatrixKind     string `protobuf:"bytes,4,opt,name=code_matrix_kind,json=codeMatrixKind,proto3" json:"code_matrix_kind,omitempty"`
	InputFileHash      string `protobuf:"bytes,5,opt,name=input_file_hash,json=inputFileHash,proto3" json:"input_file_hash,omitempty"`
	InputFileSize      uint64 `protobuf:"varint,6,opt,name=input_file_size,json=inputFileSize,proto3" json:"input_file_size,omitempty"`
}

func (x *IndexPacket) Reset() {
	*x = IndexPacket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parity_v0_Packet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IndexPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexPacket) ProtoMessage() {}

func (x *IndexPacket) ProtoReflect() protoreflect.Message {
	mi := &file_parity_v0_Packet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexPacket.ProtoReflect.Descriptor instead.
func (*IndexPacket) Descriptor() ([]byte, []int) {
	return file_parity_v0_Packet_proto_rawDescGZIP(), []int{0}
}

func (x *IndexPacket) GetBlockSize() uint64 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

func (x *IndexPacket) GetShardCount() uint64 {
	if x != nil {
		return x.ShardCount
	}
	return 0
}

func (x *IndexPacket) GetRecoveryShardCount() uint64 {
	if x != nil {
		return x.RecoveryShardCount
	}
	return 0
}

func (x *IndexPacket) GetCodeMatrixKind() string {
	if x != nil {
		return x.CodeMatrixKind
	}
	return ""
}

func (x *IndexPacket) GetInputFileHash() string {
	if x != nil {
		return x.InputFileHash
	}
	return ""
}

func (x *IndexPacket) GetInputFileSize() uint64 {
	if x != nil {
		return x.InputFileSize
	}
	return 0
}

var File_parity_v0_Packet_proto protoreflect.FileDescriptor

var file_parity_v0_Packet_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x61, 0x72, 0x69, 0x74, 0x79, 0x2f, 0x76, 0x30, 0x2f, 0x50, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1c, 0x78, 0x6f, 0x72, 0x6b, 0x65, 0x76,
	0x69, 0x6e, 0x2e, 0x62, 0x69, 0x74, 0x63, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x2e, 0x70, 0x61, 0x72,
	0x69, 0x74, 0x79, 0x2e, 0x76, 0x30, 0x22, 0xf9, 0x01, 0x0a, 0x0b, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x68, 0x61, 0x72, 0x64, 0x5f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x73, 0x68, 0x61, 0x72,
	0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x30, 0x0a, 0x14, 0x72, 0x65, 0x63, 0x6f, 0x76, 0x65,
	0x72, 0x79, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x12, 0x72, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x53, 0x68,
	0x61, 0x72, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x28, 0x0a, 0x10, 0x63, 0x6f, 0x64, 0x65,
	0x5f, 0x6d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x5f, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x64, 0x65, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x4b, 0x69,
	0x6e, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x66, 0x69, 0x6c, 0x65,
	0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x6e, 0x70,
	0x75, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x48, 0x61, 0x73, 0x68, 0x12, 0x26, 0x0a, 0x0f, 0x69, 0x6e,
	0x70, 0x75, 0x74, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0d, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x69,
	0x7a, 0x65, 0x42, 0x24, 0x5a, 0x22, 0x78, 0x6f, 0x72, 0x6b, 0x65, 0x76, 0x69, 0x6e, 0x2e, 0x64,
	0x65, 0x76, 0x2f, 0x62, 0x69, 0x74, 0x63, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x2f, 0x70, 0x62, 0x2f,
	0x70, 0x61, 0x72, 0x69, 0x74, 0x79, 0x76, 0x30, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_parity_v0_Packet_proto_rawDescOnce sync.Once
	file_parity_v0_Packet_proto_rawDescData = file_parity_v0_Packet_proto_rawDesc
)

func file_parity_v0_Packet_proto_rawDescGZIP() []byte {
	file_parity_v0_Packet_proto_rawDescOnce.Do(func() {
		file_parity_v0_Packet_proto_rawDescData = protoimpl.X.CompressGZIP(file_parity_v0_Packet_proto_rawDescData)
	})
	return file_parity_v0_Packet_proto_rawDescData
}

var file_parity_v0_Packet_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_parity_v0_Packet_proto_goTypes = []interface{}{
	(*IndexPacket)(nil), // 0: xorkevin.bitcensus.parity.v0.IndexPacket
}
var file_parity_v0_Packet_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_parity_v0_Packet_proto_init() }
func file_parity_v0_Packet_proto_init() {
	if File_parity_v0_Packet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_parity_v0_Packet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IndexPacket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_parity_v0_Packet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_parity_v0_Packet_proto_goTypes,
		DependencyIndexes: file_parity_v0_Packet_proto_depIdxs,
		MessageInfos:      file_parity_v0_Packet_proto_msgTypes,
	}.Build()
	File_parity_v0_Packet_proto = out.File
	file_parity_v0_Packet_proto_rawDesc = nil
	file_parity_v0_Packet_proto_goTypes = nil
	file_parity_v0_Packet_proto_depIdxs = nil
}
